### ISSUE TITLE
Script tag position

### ISSUE THREAD

**Issue by FFLAB** [mohole/MoholeBracketsTemplates#1]
In the jQuery framework template I'd like to have the script inclusion tag before the
`</body>`
, not between `</body>` and `</html>`. It don't change one ceppa for the functionality (I use `$(document).ready` as well) but I found it somehow disturbing the Force and world entropy. :)

**Comment by moebiusmania** [comment]
@FFLAB feel free to do whatever you preferisci on the HTML templates!
